name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
  workflow_dispatch:


jobs:
  check:
    name: Rust Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo check
  test:
    name: Rust Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo test
  fmt:
    name: Rust fmt Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo-fmt --all --check       
  # clippy:
  #   name: Rust Clippy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: cargo-clippy -D warnings
                
